spring.application.name=unext-web-services

# ===================================================================
# 1. SERVIDOR
# ===================================================================
server.port=8080

# ===================================================================
# 2. CONEXIÓN A POSTGRESQL
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/unext_db
spring.datasource.username=postgres
spring.datasource.password=unext2306.,
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# 3. JPA / HIBERNATE
# ===================================================================
# create: para destruir y volver a crear las tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# 4. JWT CONFIGURATION
# ===================================================================
jwt.secret=UnextSecretKeySuperSegura2026ParaElBackendInteruniversitario
jwt.expiration=86400000

# ===================================================================
# 5. MANEJO DE INCONSISTENCIAS / ERRORES
# ===================================================================
spring.jackson.deserialization.fail-on-unknown-properties=true

# ===================================================================
# 6. SWAGGER / OPENAPI
# ===================================================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha